# Generated by Django 2.2.3 on 2020-01-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employer_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_img',
            field=models.FileField(null=True, upload_to='static/profiles/'),
        ),
    ]
