# Generated by Django 2.2.3 on 2020-02-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0014_auto_20200227_1031'),
        ('auth', '0011_update_proxy_permissions'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0004_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiggerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Freelancer',
            new_name='Gigger',
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Shipper'},
        ),
        migrations.AlterModelOptions(
            name='gigger',
            options={'verbose_name': 'Gigger'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Gigger', 'Gigger'), ('Shipper', 'Shipper')], max_length=20, null=True),
        ),
    ]
