# Generated by Django 2.2.3 on 2020-03-31 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_messagefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='messagefile',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='messagefile',
            name='name',
        ),
    ]
