# Generated by Django 2.1.4 on 2020-02-26 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('gigs', '0019_auto_20200226_2137'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0004_customuser_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Freelancer',
            new_name='Gigger',
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Buyer'},
        ),
        migrations.AlterModelOptions(
            name='gigger',
            options={'verbose_name': 'Gigger'},
        ),
    ]
