# Generated by Django 2.2.3 on 2020-02-26 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('gigs', '0017_auto_20200226_2130'),
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0004_customuser_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Freelancer',
            new_name='Gigger',
        ),
        migrations.AlterModelOptions(
            name='gigger',
            options={'verbose_name': 'Gigger'},
        ),
    ]
