# Generated by Django 2.2.3 on 2020-02-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('gigs', '0017_auto_20200226_2130'),
        ('accounts', '0005_auto_20200226_2130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employer',
            new_name='Buyer',
        ),
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': 'Buyer'},
        ),
    ]
