# Generated by Django 2.2.3 on 2020-02-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('gigs', '0014_auto_20200227_1031'),
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0005_auto_20200227_1031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employer',
            new_name='Shipper',
        ),
    ]
