# Generated by Django 2.1.4 on 2020-02-26 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('gigs', '0019_auto_20200226_2137'),
        ('accounts', '0005_auto_20200226_2208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employer',
            new_name='Buyer',
        ),
    ]
