# Generated by Django 2.2.3 on 2020-04-02 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200331_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('current_bal', models.FloatField(default=0.0, null=True)),
                ('last_recharged', models.DateTimeField(auto_now_add=True, null=True)),
                ('exp_date', models.DateTimeField(null=True)),
                ('last_transid', models.CharField(blank=True, max_length=12, null=True)),
                ('cumulative_bal', models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='credit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Credit'),
        ),
    ]
