# Generated by Django 2.1.4 on 2020-04-02 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200331_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('current_bal', models.FloatField(default=0.0, null=True)),
                ('last_recharged', models.DateTimeField(auto_now_add=True, null=True)),
                ('exp_date', models.DateTimeField(null=True)),
                ('last_transid', models.CharField(blank=True, max_length=12, null=True)),
                ('cumulative_bal', models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=12, unique=True)),
                ('transaction_type', models.CharField(max_length=25, null=True)),
                ('transaction_amount', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='credit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Credit'),
        ),
    ]
