# Generated by Django 2.2.3 on 2020-04-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200402_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='r_switch',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
