# Generated by Django 2.1.4 on 2020-02-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200226_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Gigger', 'Gigger'), ('Shipper', 'Shipper')], max_length=20, null=True),
        ),
    ]
