<<<<<<< HEAD
# Generated by Django 3.0.3 on 2020-04-02 17:50
=======
# Generated by Django 2.1.4 on 2020-04-02 17:24
>>>>>>> 758c7368b68efefede19ca762718be7f330d8abf

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200402_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='r_switch',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
