# Generated by Django 2.2.3 on 2020-04-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_amount',
            field=models.BooleanField(default=0.0),
        ),
    ]
