# Generated by Django 2.2.3 on 2020-04-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_transaction_r_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='categories',
            field=models.ManyToManyField(to='accounts.GiggerCategory'),
        ),
    ]
