# Generated by Django 2.1.4 on 2020-02-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_giggercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigger',
            name='categories',
            field=models.ManyToManyField(to='accounts.GiggerCategory'),
        ),
    ]
