# Generated by Django 2.2.3 on 2020-02-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0016_remove_service_categories'),
        ('accounts', '0010_customuser_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiggerCategory',
        ),
    ]
