# Generated by Django 2.2.3 on 2020-05-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_shipper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagefile',
            name='message',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageFile',
        ),
    ]
