# Generated by Django 2.1.4 on 2020-05-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_shipper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='message',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='messagefile',
            name='message',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageFile',
        ),
    ]
