# Generated by Django 2.2.3 on 2020-03-30 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date_time',
            new_name='date_created',
        ),
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_file', models.FileField(null=True, upload_to='static/messages/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='accounts.Message')),
            ],
        ),
    ]
