# Generated by Django 2.2.3 on 2020-03-31 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0002_auto_20200330_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='gig',
            new_name='gigger',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('date_completed', models.DateTimeField(null=True)),
                ('gigs', models.ManyToManyField(related_name='gigs', to='gigs.Service')),
                ('order_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
