# Generated by Django 2.2.3 on 2020-03-31 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic=False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20200331_0810'),
        ('gigs', '0003_auto_20200331_0856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Gig',
        ),
        migrations.RenameModel(
            old_name='ServiceFile',
            new_name='GigFile',
        ),
        
    ]
