# Generated by Django 2.2.3 on 2020-03-31 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0004_auto_20200331_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='VAT',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='commission',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='date_to_complete',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0.0)),
                ('VAT', models.FloatField(default=0.0)),
                ('commission', models.FloatField(default=0.0)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
