# Generated by Django 2.2.3 on 2020-01-19 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employer_freelancer'),
        ('gigs', '0004_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Employer'),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
