# Generated by Django 2.1.4 on 2020-03-31 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_auto_20200331_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('additional_time', models.IntegerField(default=0, help_text='will this feature increase delivery time?')),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=1)),
                ('gig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extras', to='gigs.Gig')),
            ],
        ),
        migrations.CreateModel(
            name='GigPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Basic,Standard,Premium', max_length=10, null=True)),
                ('delivery_time', models.IntegerField(default=1, help_text='Number of days')),
                ('revision', models.IntegerField(default=1, help_text='How many times will you review?')),
                ('gig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='gigs.Gig')),
            ],
        ),
        migrations.AddField(
            model_name='gigfile',
            name='file_type',
            field=models.CharField(help_text='image,video,gif', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='extras',
            field=models.ManyToManyField(to='gigs.Extra'),
        ),
    ]
