# Generated by Django 2.1.4 on 2020-03-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0005_auto_20200331_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gigplan',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gigplan',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
