# Generated by Django 2.2.3 on 2020-03-31 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0006_auto_20200331_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='gig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='gigs.Gig'),
        ),
    ]
