# Generated by Django 2.2.3 on 2020-01-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0006_auto_20200119_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeskill',
            name='skills',
            field=models.ManyToManyField(to='gigs.Skill'),
        ),
    ]
