# Generated by Django 3.0.3 on 2020-04-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0006_auto_20200331_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigfile',
            name='file_type',
        ),
    ]
