# Generated by Django 3.0.3 on 2020-04-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0007_remove_gigfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigfile',
            name='file_type',
            field=models.CharField(help_text='image,video,gif', max_length=10, null=True),
        ),
    ]
