# Generated by Django 2.2.3 on 2020-01-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0008_resumefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(to='gigs.Skill'),
        ),
        migrations.DeleteModel(
            name='ResumeSkill',
        ),
    ]
