# Generated by Django 3.0.3 on 2020-04-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0008_gigfile_file_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GigPlan',
        ),
    ]
