# Generated by Django 2.2.3 on 2020-03-31 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0008_rating_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('additional_time', models.IntegerField(default=0, help_text='will this feature increase delivery time?')),
                ('price', models.FloatField(default=0.0)),
                ('gig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extras', to='gigs.Gig')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='extras',
            field=models.ManyToManyField(null=True, to='gigs.Extra'),
        ),
    ]
