# Generated by Django 2.2.3 on 2020-03-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0009_auto_20200331_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='extras',
            field=models.ManyToManyField(to='gigs.Extra'),
        ),
    ]
