# Generated by Django 2.2.3 on 2020-01-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0010_auto_20200119_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='Active', max_length=15, null=True),
        ),
    ]
