# Generated by Django 3.0.3 on 2020-04-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0010_gigplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='extras',
        ),
        migrations.DeleteModel(
            name='Extra',
        ),
    ]
