# Generated by Django 2.2.3 on 2020-01-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0011_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
