# Generated by Django 2.2.3 on 2020-03-31 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0011_auto_20200331_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gigplan',
            old_name='plan_name',
            new_name='name',
        ),
    ]
