# Generated by Django 2.2.3 on 2020-03-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0012_auto_20200331_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigfile',
            name='file_type',
            field=models.CharField(help_text='image,video,gif', max_length=10, null=True),
        ),
    ]
