# Generated by Django 3.0.3 on 2020-04-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0012_auto_20200401_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='description',
        ),
    ]
