# Generated by Django 2.2.3 on 2020-01-22 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0012_job_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50, null=True)),
                ('start_price', models.FloatField(default=0.0)),
                ('end_price', models.FloatField(default=0.0)),
                ('experience', models.IntegerField(default=0)),
                ('service_detail', models.TextField(null=True)),
                ('rating', models.FloatField(verbose_name=0.0)),
                ('gig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
