# Generated by Django 2.2.3 on 2020-01-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0013_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
