# Generated by Django 2.2.3 on 2020-02-27 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0013_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Gig'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='end_price',
        ),
        migrations.AlterField(
            model_name='service',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='ServiceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicefile', models.FileField(null=True, upload_to='static/services/')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='gigs.Service')),
            ],
            options={
                'verbose_name': 'Gig File',
            },
        ),
    ]
