# Generated by Django 3.0.3 on 2020-04-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0013_remove_extra_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
