# Generated by Django 2.2.3 on 2020-02-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200227_1032'),
        ('gigs', '0014_auto_20200227_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(to='accounts.GiggerCategory'),
        ),
    ]
