# Generated by Django 2.2.3 on 2020-01-26 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0015_auto_20200126_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicefile', models.FileField(null=True, upload_to='static/services/')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='gigs.Service')),
            ],
        ),
    ]
