# Generated by Django 2.2.3 on 2020-04-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0015_auto_20200401_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.IntegerField(default=0),
        ),
    ]
