# Generated by Django 3.0.3 on 2020-02-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_giggercategory'),
        ('gigs', '0016_remove_service_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(to='accounts.GiggerCategory'),
        ),
    ]
