# Generated by Django 2.2.3 on 2020-02-26 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0016_servicefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Gig'},
        ),
        migrations.AlterModelOptions(
            name='servicefile',
            options={'verbose_name': 'Gig File'},
        ),
    ]
