# Generated by Django 2.2.3 on 2020-04-03 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_customuser_categories'),
        ('gigs', '0016_order_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=50, null=True)),
                ('detail', models.TextField(help_text='This should say what the client wants', null=True)),
                ('updated', models.BooleanField(default=False)),
                ('time_updated', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('time_completed', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('created', 'created'), ('quoted', 'quoted'), ('transit', 'transit'), ('completed', 'completed')], default='created', max_length=20, null=True)),
                ('date_time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('time_created', models.TimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(help_text='To what specialty do we classify this request', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.GiggerCategory')),
                ('created_by', models.ForeignKey(help_text='Who actually created the request?', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request_by', models.ForeignKey(help_text='The client who created this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_submitted', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_submitted', models.DateField(auto_now_add=True, null=True)),
                ('time_submitted', models.TimeField(auto_now_add=True, null=True)),
                ('updated', models.BooleanField(default=False)),
                ('time_updated', models.DateTimeField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('time_accepted', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(help_text='Who created the quote?', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='gigs.Request')),
                ('submitted_by', models.ForeignKey(help_text='Who was this quote created for?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
