# Generated by Django 2.2.3 on 2020-04-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0017_quote_request'),
        ('gigs', '0017_auto_20200403_1112'),
    ]

    operations = [
    ]
