# Generated by Django 2.2.3 on 2020-05-08 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0018_merge_20200430_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gigs.Gig'),
        ),
    ]
