# Generated by Django 2.2.3 on 2020-04-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0018_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
