# Generated by Django 2.1.4 on 2020-05-08 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0018_merge_20200430_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
