# Generated by Django 2.2.3 on 2020-02-26 21:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0018_auto_20200226_2136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gig',
            new_name='Service',
        ),
    ]
