# Generated by Django 2.1.4 on 2020-05-08 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0019_auto_20200508_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gigs.Gig'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
