# Generated by Django 2.2.3 on 2020-05-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0020_auto_20200508_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='gig',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_to',
        ),
    ]
